#!/bin/bash

DIRECTORY=${PWD##*/}

sudo rm -rf /var/www/projects/$DIRECTORY/
echo "Copying Contents of current folder to '/var/www/projects'..."
cp -R ../$DIRECTORY /var/www/projects/
rm -rf /var/www/projects/$DIRECTORY/.git
rm /var/www/projects/EngineCompare/deploy
rm /var/www/projects/EngineCompare/README.md
sudo chown -R aaron:www-data /var/www/projects/$DIRECTORY
